name: Publish Repo

on:
  push:
    branches:
    - 'main'
  workflow_dispatch:

jobs:
  publish:
    name: "Publish"
    runs-on: ubuntu-latest
    steps:
    - uses: duerrsimon/gh-action-repo-selective-sync@master
      with:
        recipe-file: '.publish/recipe.yml'
        token-source: ${{ secrets.GITHUB_TOKEN }}
        token-target: ${{ secrets.TARGET_PAT }}
